### ISSUE TITLE
[Backend] As user, I can download a PDF of the search result

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/ic-rails-huey-toby#16]
## Why

A user can download a PDF of the HTML search result

## Acceptance Criteria

- A user can only download the search results he uploaded, based on the authorization token

- Add a new field called `pdf` of type `binary` to the `search_results` table 

- Create a new endpoint: `GET api/v1/export?searchResultId={id}`

    - **Header**: Authorization (bearer token)
    -  **Request**: `searchResultId={id}`
    - **Response**: HTTP Code
    
- Write unit and integration tests
- Handle errors: Unauthorized, ... 
- There are two approaches to managing this, when do we generate the PDF?
    - Once the user executes the API (better for database memory) 
    - Once the job has been completed (better UX)
    
Preferably go with the first approach, if the UX is acceptable

**Note**: Use Grover to generate the PDF from the HTML code

## Design
N/A

## Resources
https://github.com/Studiosity/grover

**Comment by olivierobert** [comment]
@Tuubz You can check this recent retro presentation for the PDF generation: https://docs.google.com/presentation/d/1St530vEBmwZDE7JV5JfAl_pBI4YNdhf7wt4haLKZ2Jo/edit?usp=sharing
