### ISSUE TITLE
Set up API routes

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/ic-rails-huey-toby#24]
## Why

Prepare the routes properly for future endpoints

## Acceptance Criteria

Make sure that all the endpoints start with `api/v1` (Update routes, controllers, ...)

## Design

N/A

## ResourcesN
N/A

**Comment by olivierobert** [comment]
@Tuubz That story can be done in 5 minutes 😅 It is just a matter of adding a namespace: https://guides.rubyonrails.org/routing.html#controller-namespaces-and-routing

**Comment by Tuubz** [comment]
@olivierobert 0 points it is then!
