### ISSUE TITLE
Set up DB for persistent data

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/ic-rails-huey-toby#4]
## Why

Data must be persisted, so we must set up a PostgreSQL database that works with Heroku.

## Acceptance Criteria

Support a database for staging and production on Heroku.

## Design

N/A

## Resources

- https://www.postgresql.org/
- https://devcenter.heroku.com/articles/heroku-postgresql

**Comment by hoangmirs** [comment]
This can be merged with the CD setup, as this is just a small task, we just need to enable the Heroku Postgres add-on on the Heroku 💪

**Comment by Tuubz** [comment]
@hoangnguyen92dn If that's the case, shall I take over #3? 

Then you can start working on an issue from the next sprint 🚀

**Comment by hoangnguyen92dn** [comment]
@Tuubz Okie. So I will update the assignee 🙏
